[flagged_events]
field.id = string
field.uid = string
field.flag = number
field.added_by = string
field.added_when = number
field.idx = string
field.description = string
field.mitre_tactic = string
field.status = string